### ISSUE TITLE
print.R6 should display methods with () in different place

### ISSUE THREAD

**Issue by wch** [r-lib/R6#173] opened 2018-11-28 18:55 UTC
This is what it currently prints:

```
<WebServer>
  Inherits from: <Server>
  Public:
    getHost: function () 
```

It should be:

```
<WebServer>
  Inherits from: <Server>
  Public:
    getHost(): function
```

**Comment by hadley** [comment] 2020-04-03 14:00
Duplicate of #127

**Closed by hadley** 2020-04-03 14:00 UTC
